# Generated by Django 5.2.9 on 2025-12-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('type_of_product', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('mobile_no', models.IntegerField(max_length=10, unique=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusID', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='SS_BackendApp.product')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='SS_BackendApp.usermodel')),
            ],
        ),
    ]
