# Generated by Django 5.2.9 on 2025-12-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_no',
            field=models.IntegerField(unique=True),
        ),
    ]
