# Generated by Django 5.2.9 on 2025-12-11 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0003_usermodel_address_alter_order_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='refresh_token',
        ),
        migrations.CreateModel(
            name='refreshTokenStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SS_BackendApp.usermodel')),
            ],
        ),
    ]
