# Generated by Django 5.2.9 on 2025-12-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0004_remove_usermodel_refresh_token_refreshtokenstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtokenstore',
            name='id',
        ),
        migrations.AlterField(
            model_name='refreshtokenstore',
            name='jti',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
