# Generated by Django 5.2.9 on 2025-12-11 08:16

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0005_remove_refreshtokenstore_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtokenstore',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='refreshtokenstore',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refreshtokenstore',
            name='jti',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
