# Generated by Django 5.2.9 on 2025-12-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0007_remove_usermodel_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
