# Generated by Django 5.2.9 on 2025-12-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0008_alter_usermodel_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
