# Generated by Django 5.2.3 on 2025-12-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0011_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='productID',
            field=models.JSONField(),
        ),
    ]
