# Generated by Django 5.2.3 on 2025-12-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0012_order_total_price_alter_order_productid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pin_code',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
