# Generated by Django 5.2.3 on 2025-12-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0013_usermodel_city_usermodel_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='total_order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.JSONField(null=True),
        ),
    ]
