# Generated by Django 5.2.3 on 2025-12-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0014_remove_usermodel_city_remove_usermodel_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.JSONField(default=list),
        ),
    ]
