# Generated by Django 5.2.3 on 2025-12-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0015_alter_usermodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_of_product',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
