# Generated by Django 5.2.3 on 2026-01-05 07:00

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0021_alter_usermodel_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('cartItem', models.JSONField(default=list, null=True)),
                ('customerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SS_BackendApp.usermodel', verbose_name='customer ID')),
            ],
        ),
    ]
