# Generated by Django 5.2.3 on 2026-01-09 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0022_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex'), ('kids', 'Kids')], max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='SS_BackendApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('MALE_TOP', [('XS_34', 'XS (34)'), ('S_36', 'S (36)'), ('M_38', 'M (38)'), ('L_40', 'L (40)'), ('XL_42', 'XL (42)'), ('XXL_44', 'XXL (44)'), ('3XL_46', '3XL (46)'), ('4XL_48', '4XL (48)')]), ('MALE_BOTTOM', [('XS_28', 'XS (28)'), ('S_30', 'S (30)'), ('M_32', 'M (32)'), ('L_34', 'L (34)'), ('XL_36', 'XL (36)'), ('XXL_38', 'XXL (38)'), ('3XL_40', '3XL (40)'), ('4XL_42', '4XL (42)')]), ('FEMALE_TOP', [('XS_32', 'XS (32)'), ('S_34', 'S (34)'), ('M_36', 'M (36)'), ('L_38', 'L (38)'), ('XL_40', 'XL (40)'), ('XXL_42', 'XXL (42)'), ('3XL_44', '3XL (44)'), ('4XL_46', '4XL (46)')]), ('FEMALE_BOTTOM', [('XS_26', 'XS (26)'), ('S_28', 'S (28)'), ('M_30', 'M (30)'), ('L_32', 'L (32)'), ('XL_34', 'XL (34)'), ('XXL_36', 'XXL (36)'), ('3XL_38', '3XL (38)'), ('4XL_40', '4XL (40)')])], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='products/variants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='SS_BackendApp.product')),
            ],
            options={
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
