# Generated by Django 5.2.3 on 2026-01-09 19:34

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0023_category_products_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
    ]
