# Generated by Django 5.2.3 on 2026-01-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0024_alter_category_id_alter_products_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SS_BackendApp.products'),
        ),
    ]
