# Generated by Django 5.2.3 on 2026-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0028_products_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantsize',
            name='updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
