# Generated by Django 5.2.3 on 2026-07-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0029_variantsize_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
