# Generated by Django 5.2.3 on 2026-07-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0030_alter_usermodel_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='mobile_no',
        ),
    ]
