# Generated by Django 5.2.3 on 2026-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0031_remove_usermodel_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
