# Generated by Django 5.2.3 on 2026-07-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0035_coupon_notificationtemplate_order_tracking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='channel',
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='statusID',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='CONFIRMED', max_length=20),
        ),
    ]
