# Generated by Django 5.2.3 on 2026-08-06 14:52

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0037_usermodel_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tracking_id',
            new_name='awb_id',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='returned_order',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('productNo', models.IntegerField()),
                ('return_awb_id', models.CharField(max_length=100)),
                ('delivered_awb_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('return_shipped', 'Returned Shipped'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('refund', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_orders', to='SS_BackendApp.usermodel')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_orders', to='SS_BackendApp.order')),
            ],
        ),
    ]
