# Generated by Django 5.2.3 on 2026-08-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0038_rename_tracking_id_order_awb_id_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
