# Generated by Django 5.2.3 on 2026-08-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0039_order_discount_order_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='finalized',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='statusID',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled'), ('DELIVERED', 'Delivered'), ('RETURNED_REQUEST', 'Returned Request'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED_SHIPPED', 'Returned Shipped'), ('RETURNED', 'Returned')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='returned_order',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('return_shipped', 'Return Shipped'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('pending_refund', 'Pending Refund'), ('refunded', 'Refunded')], default='approved', max_length=20),
        ),
    ]
