# Generated by Django 5.2.3 on 2026-08-07 15:44

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0040_remove_order_finalized_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='productID',
        ),
        migrations.AlterField(
            model_name='order',
            name='statusID',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED_TO_ORIGIN', 'Returned to Origin')], default='CONFIRMED', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('variant_size_id', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('variant_image', models.CharField(blank=True, max_length=500, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('item_status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('RETURN_REQUESTED', 'Return Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURN_SHIPPED', 'Return Shipped'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded')], default='DELIVERED', max_length=20)),
                ('return_reason', models.CharField(blank=True, max_length=255)),
                ('return_requested_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='SS_BackendApp.order')),
            ],
        ),
    ]
