# Generated by Django 5.2.3 on 2026-08-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0041_remove_order_created_at_remove_order_productid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_awb_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
