# Generated by Django 5.2.3 on 2026-08-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0042_orderitem_return_awb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_awb_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
