# Generated by Django 5.2.3 on 2026-08-08 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0043_orderitem_order_awb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='created_At',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
