# Generated by Django 5.2.3 on 2026-08-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0044_usermodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
