# Generated by Django 5.2.3 on 2026-08-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0045_order_delivery_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AddField(
            model_name='order',
            name='productID',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='order',
            name='statusID',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
