# Generated by Django 5.2.3 on 2026-08-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0047_alter_order_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productID',
            field=models.JSONField(default=dict),
        ),
    ]
