# Generated by Django 5.2.3 on 2026-08-23 18:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0049_order_delivery_charge_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartItem',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('razorpay_order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('productID', models.JSONField(default=dict)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('delivery_charge', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('address', models.JSONField(default=dict)),
                ('mobile_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('statusID', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('couponID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='SS_BackendApp.coupon')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='SS_BackendApp.usermodel')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='SS_BackendApp.order')),
            ],
        ),
    ]
