# Generated by Django 5.2.3 on 2026-09-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0051_remove_payment_order_id_order_couponcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentID',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='SS_BackendApp.payment'),
        ),
    ]
