# Generated by Django 5.2.3 on 2026-09-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0052_alter_order_paymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_order_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
