# Generated by Django 5.2.3 on 2026-09-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0053_coupon_max_order_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Total_price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='couponID',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='couponCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
