# Generated by Django 5.2.3 on 2026-09-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0054_rename_total_price_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='couponDiscount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
