# Generated by Django 5.2.3 on 2026-09-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SS_BackendApp', '0055_payment_coupondiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='couponDiscount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='couponDiscount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
